### PR TITLE
Update PDK layout

### PR DESCRIPTION
**Pull request by ekohl**
This copies all files from puppetlabs-postgresql since I can't use PDK due to a missing puppet-module-posix-default-r3.0 gem.

### CODE REVIEW

**Comment by ekohl** [comment]
@david22swan (or not sure who else to ping) I could use some review here. This is blocking https://github.com/puppetlabs/puppetlabs-xinetd/pull/121.

**Comment by binford2k** [comment]
Could we get a @puppetlabs/modules member to help get this module onboarded to cloud ci & autorelease please?

**Comment by ekohl** [comment]
Reminder. This is literally the last module I need to mark compatible with Puppet 7 and it's really ironic that it's in the puppetlabs namespace. If Puppet doesn't maintain this module anymore, can we move it Voxpupuli instead?

**Comment by ekohl** [comment]
Foreman has stopped using this module so I no longer have an interest in it.

**Pull request closed without merging**
