### PR TITLE
allow puppetlabs-stdlib 5.x

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Comment by bastelfreak** [comment]
https://github.com/puppetlabs/puppetlabs-xinetd/blob/master/.fixtures.yml#L5
this should be adjusted so the tests run against master.

**Comment by mmoll** [comment]
done.

**Comment by mmoll** [comment]
If anybody could get this in and release a new version on the forge, that would be super helpful... :pray:

**Comment by bastelfreak** [comment]
The related issue is https://tickets.puppetlabs.com/browse/MODULES-7767

**Pull request merged**
