### PR TITLE
fix default_user/default_group and add tests

### PR DESCRIPTION
**Pull request by sethlyons**
the default_user and default_group functionality wasn't working as designed.  additionally, 671a8cc6d705ac98bcac94935aa452b3dc6ccdd1 made everything break on freebsd.  in this branch i fixed default_user and default_group, and i also added tests.

### CODE REVIEW

**Comment by sethlyons** [comment]
connected to https://tickets.puppetlabs.com/browse/MODULES-2313

**Comment by bmjen** [comment]
Thanks @sethlyons! This looks good. The tests need to be fixed and the branch needs to be rebased first.

**Comment by sethlyons** [comment]
all set.

**Comment by sethlyons** [comment]
hi -- can you please merge this and do a new release for forge?
thanks!

**Pull request merged**
