### PR TITLE
Add support for 'nice' argument.

### PR DESCRIPTION
**Pull request by decibelhertz**
Add support for 'nice' argument in a server config, with error checking and spec tests.  Supports nice -19 to nice 19.

### CODE REVIEW

**Comment by mhaskel** [comment]
@decibelhertz This looks good, but needs to be rebased. Thanks!

**Comment by decibelhertz** [comment]
Think we're good to go now?

**Comment by mhaskel** [comment]
Thanks @decibelhertz !

**Comment by decibelhertz** [comment]
Thank you.

**Pull request merged**
