### PR TITLE
Support newer versions

### PR DESCRIPTION
**Pull request by ghoneycutt**

### CODE REVIEW

**Comment by ghoneycutt** [comment]
Bump.

Can I get this merged, please?

**Comment by ekohl** [comment]
I think you can close https://github.com/puppetlabs/puppetlabs-xinetd/pull/50 since this includes the same commit.

**Comment by ghoneycutt** [comment]
@DavidS Could you please review this?

**Comment by ghoneycutt** [comment]
@DavidS thanks

**Comment by ghoneycutt** [comment]
@DavidS Could you please tag this release to denote the change in master?

**Pull request merged**
